# server.document-root = "/var/www/servers/www.example.org/pages/"
server.document-root = "/home/bctnry/workspace/cursed-blog-app/wwwroot/"
server.port = 3000   # (non-standard port for testing)
server.modules += ( "mod_cgi" )
static-file.exclude-extensions = ( ".fcgi", ".php", ".rb", "~", ".inc", ".awk", ".rec" )
index-file.names = ( "index.awk" )
cgi.assign = ( ".awk" => "" )
