var.app_root = "/home/bctnry/workspace/cursed-blog-app"
server.document-root = var.app_root + "/wwwroot/"
server.port = 3000   # (non-standard port for testing)
server.modules += ( "mod_setenv", "mod_cgi" )
static-file.exclude-extensions = ( ".fcgi", ".php", ".rb", "~", ".inc", ".awk", ".rec" )
setenv.add-environment = (
    "AWKPATH" => var.app_root + ":/usr/local/share/awk"
)
index-file.names = ( "index.awk" )
cgi.assign = ( ".awk" => "" )
